name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # или твоя основная ветка

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # чтобы Nextra правильно показывал даты изменений

      - uses: actions/setup-node@v3
        with:
          node-version: '20' # Next.js 14+ требует Node 20+

      - run: npm ci 
      - run: npm run build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
